### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by paranzchoy** [paranzchoy/rapidpos#224]
UI Customizations
- [ ] square buttons
- [ ] change themes
- [x] remove help buttons
- [ ] remove links
- [x] disabled getting started videos
- [ ] Frappe Icons
- [ ] ERPNext Icons

---
UI customization login page

- [ ] background image (jacobs breadnuts)
- [x] disable website
- [x] remove powered by ERPNext

---
Remove menus
- [ ] remove POSAwesome workspace
- [ ] Add POSAwesome links to Retails
- [ ] disable other domains
- [ ] Remove Qualities
- [ ] Remove Utilities
- [ ] Remove CRM
- [ ] Remove Loans
---
- [ ] Data migration
- [ ] User training
- [ ] Subitems customization

**Comment by JMBodz** [comment]
Users
- Administrator is ours   -- All Modules Access
- JacobsAdministrator needed? -- Limited Modules Access

**Comment by JMBodz** [comment]
Data Migration #202 .
